language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 0fYEWhDpeQ5l/aXke4D3rZ2Y8J9v2y+IYa7Q75b2pqdawvBFu8umkiuz9uZXmGF2rDWJpYk1NAJW5cjZhcS8OGYpOEIlf8RFqVnWB+6tp9zS+HPu4xTjitkonRArOqQpLGRcH6oVfYTF+cpp/nBkv6HUPAxn/Dx0VbsFquu4PNr/xDD3Boe6xQavU9ZrwRBzTU8oT1y8CQiGdsOsxWUbWnacCo30lkUoNBzhAZzHUWRHkgQW9CMcFiXElCfmPb+h5WHXZTI3hQG6EohOCdwJZk3quK9lj+n+2h7IEWHx19rdt7iS/oM/teDigDTT0738Mz5Bowo6HLA7ZtkmVCO9n08noQOj83g7qQfGpEmi6inozSzdriM/hB1lGmjMEJG1pCQ6pLX0O+7L8wzYr3QBSMGOxr6zaRkZ+KLEQFhqWULoDfOL8qGSVmhxvziH1YK812WXIT0aefOfadjokjrlvC19hHBHMNKTJEAghNBMCfvmL0rwhCZzNhY3DfzWZAst2SujoMczXSOffYm8zeA+pKP9uOGrzT0ZSM9lDVGVakRVcCaoCJ33uEkKi2G6n8MCpkcA6lTREdnD0MmvtNZXzO9hxsX/96CdxwXAc7bxasC3kSqNjVy8fPLg25VQzQfTQbbg8wJwQlKXks/UeRdFby1DHiGl+znPvzXK7e2W8eI=
