language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: WdeyilS3MkDU6zaRAEmir5RuZ/ejj7G21xuS4c4aSsgmow9/EeKguDiGXSv5h3r6ob/WaYpsqaOpyfK4mQL49wE8cBDuq1r3fXEY65+Zu0IFuvqCJnQyAh4KaR5YSwVbtCldcWjK1x1ORy3T8XCLzDMd/Xd7DAY/bMkJtaaqeqwq6ZlKiklmjIIX+Z0fJ1WzMUbQr6ui8CbA7+j3dqS47rW631aUZwk8aCzumAmnt7SNqXI6BNq/8rB3qe+AcNR6a+3mVeew3NgBU5bPzaUN1cZ1ooja7lRGiO5qABBDh9IajjNHfxNAU3Iu+MwqvdVbviNt1k5epB3AA2bDE46D2CTOo8hlSqFbp0leXQ/q4LuvaTEejgN3cUeGgZamlgbpSjC81taXX4kHddRKAdukyuAVNetJyTeWQB7cahBafT5gnkHcsrKqsQKFNMo/17UL3VVOWqNx8+TSTt3sLGsU59ucGmUmjYPFfWT0E7DflQFKB5z+FX1RZKviCta3CD+mQznWdYRxg8e/NBMU4/B/a6Yd8TfJQ6kO14oo7UGNS9hzo7OAFdlCSzc6CkjXVE9UwI0r2tXfEkUH/0wsVBFKrYKrK65FQzRzLLsHhyYOhvlf/Xtl72I8yNogtsgMj2mD5ZWXvz09fIDxEiph3cP0BeveHhFFFeHoNGE4ZFi3Ue4=
