language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  # Production Firebase token:
  # token:
    # secure: Ac9BTslv8zmRUI6LOyDmfEnJ/eRZ+EPxKKz4Q5NUUohXADpE3B3jC7CMdyTm7qDD633gev4Nx1CsLZ3yYatVQGIpq24UufZ8Qp86Ifg+i2/Ii6/mSuROfhzGfljZfeGNWIQJZXjgPRtdepA2O3XalTBVFUeJoQZt9o5lVwDgmAdS1R+P1vM3dJ1towuZXUH+EJc2lpPmKtTYL0wo/XMRFaBUOmfSHQN8gvjVoMyPzrW3S4Sigwg8YVG5tjdr5EFWX8Mn0x10NfBIxczYGMFtMXCdoVYR+Q7Uq85gSbBtBk1FQ9W4A0bhbUvKiM012+snKWzKG3FwTR1FrhuRLeGsUz3GG+ZnlTL0iDxbrmgenib2aw2he/rR0i52kNhsjCFT/SwVL/eMZhuJTLsU719r7ykvPTdx+4vp89fZccgCMA/lydH8BOiGjfT3xL1A/jsvEtF6MfskrwzYg/S0xoyRqyjZGOCq27IxPaYxS6MGCOhOlSnCfdYZ776VECrYSJ/a4V/nwMg5GMeDaTYKcw8eMwWrDiVo1ALCxksYfSdnBxxjthloUKnE71jEKRfbVsLv7Y5qqUjyKeASROlcohMbH7FVmQIm/16yXs2w7a5yjeYp3UpFz7yFtfcJH1LBfTmANM+1lfbqBRpXAxmljkanc+ADKxE8OOgmIgiVrlIsFsM=
  # Test environment Firebase token
  token:
    secure: H1gfzu6IYp80RdVYtCEqTptKaj7gCj0QIOtdZ0XDHb442ohPYiV0qOjTT8UM1VczmL74sqpxv4pUvcdKYPrVEnOVo5fRqM9u4xN8eYEfQb8UA3C2xAHGT7tr7fOuKfDt66vsdBxqP+E8coPud7QkETbLchbXF3c7W5kyte5jujUEgNG2AuCpesYXJBXYDuy8fgvvMK0xcymkjBqhyIisT0O9aIeW4FAgQnZ+2gitPN86eYsLrI4WG3fXpP18BQma+GCsG0nwHgVrTs8dJQlCjTXQ1UotJNyBRzf6dhXYnX/s1aQD2GT8SnSnoLsiOYxhX/WDQD75D3Vgs5zy+ngGNDjhPYg3Kjh+aXklYgxporaVrT1NUTOTJ1JEyUWyjBsziImMp+T6Xe23D/bTnx0hi/mGLbpw7E1+slVy5qVnb5jLjKN4up8XWspujcPtmm7pMkxWZGQXjxj+3XZ60Lo/ix9TRv4NcRvFeeAGmXQEoD5ETABEx+BItDK68dkkSGKNBTlhRv2/AjlODnXgmPgo/VlFxWT9ycHRh8cpzUpvxO1Sl6rCQ6WHe3T16oJyui5Z8axB8jwto3IziXG0DcajMeZ+WkMnpEBfszGuX9FsxLEB7zybbOeJFPlZrrvnVY8yCj/wOd7Ihghl6JkXhMLVL0m1cZnmaAkfDw7LdLwwaiQ=
