language: node_js
node_js:
  - "12"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Ac9BTslv8zmRUI6LOyDmfEnJ/eRZ+EPxKKz4Q5NUUohXADpE3B3jC7CMdyTm7qDD633gev4Nx1CsLZ3yYatVQGIpq24UufZ8Qp86Ifg+i2/Ii6/mSuROfhzGfljZfeGNWIQJZXjgPRtdepA2O3XalTBVFUeJoQZt9o5lVwDgmAdS1R+P1vM3dJ1towuZXUH+EJc2lpPmKtTYL0wo/XMRFaBUOmfSHQN8gvjVoMyPzrW3S4Sigwg8YVG5tjdr5EFWX8Mn0x10NfBIxczYGMFtMXCdoVYR+Q7Uq85gSbBtBk1FQ9W4A0bhbUvKiM012+snKWzKG3FwTR1FrhuRLeGsUz3GG+ZnlTL0iDxbrmgenib2aw2he/rR0i52kNhsjCFT/SwVL/eMZhuJTLsU719r7ykvPTdx+4vp89fZccgCMA/lydH8BOiGjfT3xL1A/jsvEtF6MfskrwzYg/S0xoyRqyjZGOCq27IxPaYxS6MGCOhOlSnCfdYZ776VECrYSJ/a4V/nwMg5GMeDaTYKcw8eMwWrDiVo1ALCxksYfSdnBxxjthloUKnE71jEKRfbVsLv7Y5qqUjyKeASROlcohMbH7FVmQIm/16yXs2w7a5yjeYp3UpFz7yFtfcJH1LBfTmANM+1lfbqBRpXAxmljkanc+ADKxE8OOgmIgiVrlIsFsM=
