language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Yq8mMagHBedcHCzT5TMZpDDJ7It5bEvnO1E5ZSBQpey0pb9rDHZq+NntzMqN+BRSVnEhlhA2X3iW+tK391Yq2sNJNxVB3NjsudbeMO1/foiduiF2IiBSd7kE4RpZCZGjkZhyaCHWhmKk3NC8pmGPCUQ1Oi5Liu8J3LYnrQSMLoIif3NWDBPjzhiyIoF5jL6cO0RBvHbcAhQM1qi5edAASiEuVvq99fp8wxQx9uhEIWYgvpGuZnlGrK9+lzErk44P4TAJ+NqIwUnDjDM7GMY6hxjRoH96LbBgJlw2xWI0ptkjs0uOW56okmNdPqu1YXhnLXIhxWPSaifj42YO4FC/TvMfKhT4t7YFjCD75mirUGgN4pHJkmiWWxbN+NKxc0Z4OUz6dvALc03Skstlm1AkRr4I1xsfQEQtG4p0DIpgzl5veotWEgjX/fX8YNooiKZ0oiWZDZzp7Nm/6nfX/Amwk0hF5fQsUBbrnPJuR2/+hleTDE5mJSy6b3lZiXcK+zKHvZ53TCnb7+N2RIDCDAMpxkPh5QtJXyhTDa6Bg1PYFEhZ4vlRN798xiD8vfzK6EH6Tv2Z0uXg7x3dzsVTh33xfai3dDLjJjMLdA6oa0VOOT7TKirn4aqbXYhHnTIXhxGSs2CBYM2b+L1yJargaD+sr58vE/EqY2+1Yt+XxNC1krA=
